# Data Source {#datasource}

The storm track data presented in the analysis is downloaded from [National Hurricane Center and Central Pacific Hurricane Center](https://www.nhc.noaa.gov/data/#hurdat), which is also known as the Atlantic hurricane database [HURDAT2: 1851-2018] (https://www.nhc.noaa.gov/data/hurdat/hurdat2-1851-2018-120319.txt) and the [HURDAT](https://www.aoml.noaa.gov/hrd/hurdat/comparison_table.html.) data is downloaded from the [NOAA’s Atlantic Oceanographic and Meteorological Laboratory] (https://www.aoml.noaa.gov/). 

We choose to work with these data because they provide us with updated, complete and accurate information about hurricanes over the past 150 years (1851 - 2018). Since the Atlantic hurricane activity has shown very strong year-to-year and decade-to-decade variability, longer records or hurricanes are much needed. 

In addition, we have also gathered the directly observed Atlantic Meridional Overturning Circulation (AMOC) index at 26 oN available for the period 27, 33 2004–2014, which is obtained from the [RAPID-WATCH MOC monitoring project] (www.rapid.ac.uk/rapidmoc). This is for the purpose of analyzing the linkage between hurricane frequency and climate variability, as well as the causes of the changes in Atlantic major hurricane frequency.

Furthermore, all the low-pass filtered data are obtained using the R function “filtfilt” with a Hamming window based low-pass filter at a 10-year cutoff period. One important thing to note about the names of hurricanes is that there are six names lists that have been used in rotation and re-cycled every six years. This means that there can be more than one hurricanes having the same name but happened in different years. We have tackled this problem by giving each hurricane a unique `storm-id`.

